### PR TITLE
Introduce GSettings configuration storage system

### PR DESCRIPTION
**Pull request by markuspg**
This pull request aims at introducing GSettings as new configuration storage system without losing the ability to import settings from the previous configuration systems.

I would propose to revert my started attempt of just dropping the other configuration systems (as #30) does, completing this pull request afterwards and then creating a release `2.5.0` (which is not really advertised, but just mentioned in the documentation as an update path for existing installations) which allows migrating data from GConf and older to GSettings. 

After `2.5.0` all the old configuration systems could then be dropped and `3.0` could focus on GSettings.

### CODE REVIEW

**Comment by markuspg** [comment]
**Important**: This is kind of a "refined draft"! If we decide to follow this path I plan to merge #30 first and then rebase this one and do some extensive testing. The code is generally complete, but not properly tested yet.

**Comment by oskarb** [comment]
Yes, I think it's good practice to have an upgrade path that respects existing configuration, even for  a very old application. If it can reasonably be done. I thought about it when reviewing the first gsettings introduction - at the time I decided it wasn't important enough to mention, but if you also feels this way and it's doable, I think that's the way to go.

Btw, did you consider the *Data conversion* section in https://docs.gtk.org/gio/migrating-gconf.html?

**Review by oskarb — DISMISSED** [review]
I'm unsure if you intended to do more here or if this was ready. But I've looked through it and I do not have any structural objections. Looks good to me.

**Comment by markuspg** [comment]
@oskarb Thank you for the review. I had to hunt down one bug (the creation dialog for the storage file being shown again and again - seems to have been a faultily written option name preventing a proper save on application shutdown) and added the usage of _delay-apply_ mode after reading the documentation shared by you. The old code suggested using `GConfChangeSet` to set all options as once. With `GSettings`  this was easily doable.

**Pull request merged**
